### ISSUE TITLE
im getting a error that the SMS is not found

### ISSUE THREAD

**Issue by noman1295** [floatinghotpot/cordova-plugin-sms#12]
wen i click on start or stap watch or send sms it gives me a error that i SMS is not defined 
i working on hybrid app 

thank you

**Comment by floatinghotpot** [comment]
Please copy the index.html under test folder for testing purpose. 

Or, run following commands for testing:
```bash
[sudo] npm install -g plugin-verify
plugin-verify cordova-plugin-sms
```
