### ISSUE TITLE
Alert SMS is not supported

### ISSUE THREAD

**Issue by c316** [floatinghotpot/cordova-plugin-sms#15]
If I'm getting an alert with the error "SMS is not supported" what might I be doing wrong? 

Thanks

**Comment by floatinghotpot** [comment]
How did you produce the alert ？

**Comment by c316** [comment]
I am using this plugin within Meteor. I have setup the test app and I'm using sendSMS through the test form to send to another emulator. I'm able to use the native app to send text messages, but I get that error anytime I try to run the app.

**Comment by floatinghotpot** [comment]
Tell me more info, what did you do step by step, and any logs or other error messages?

**Comment by dimxasnewfrozen** [comment]
I'm also getting this message. I can't get this plugin to work at all for the life of me. I'm trying to run it from the emulator. I'm running the code as it from the demo.

**Comment by floatinghotpot** [comment]
You have to run it in real device, as your emulator has no SIM card.
