### ISSUE TITLE
sendSMS do no action in ios

### ISSUE THREAD

**Issue by firaskudsy** [floatinghotpot/cordova-plugin-sms#16]
hi, i used this plugin in my android - ionic framework app, now i want to do the ios side, but something ging wrong,

when the execute reach the line 

SMS.sendSMS( ........

nothing happen , no error in console .. no sms sent .. nothing !!

any help ?

**Comment by simokhalil** [comment]
Hi,
The core native code of this plugin - which is executed in the background of the Ionic/Cordova Javascript code - has only been written for Android (Java). It then won't work for iOS since the concerned part (in Swift) has not been developped.

**Comment by floatinghotpot** [comment]
Yes, this plugin is only for Android. The native code for iOS is not developed at all.
