### ISSUE TITLE
SMS object not available in IONIC framework for android.

### ISSUE THREAD

**Issue by rc12** [floatinghotpot/cordova-plugin-sms#17]
I tried this plugin in IONIC. But the SMS object is coming as undefined in android device(One Plus One). I'm pretty sure it's being called after "device is ready".

**Comment by rc12** [comment]
Sorry! It works. You need to wait for app to load properly. Ideally you should call "SMS" object or its method on user interaction with the app.

**Comment by joseangelmr** [comment]
Hi!,

Plugin compatible with ionic?. some example?

Thanks you..
