### ISSUE TITLE
Plugin not found on iOS

### ISSUE THREAD

**Issue by chrisbenseler** [floatinghotpot/cordova-plugin-sms#18]
Installed using the following command:
cordova plugin add com.rjfun.cordova.sms

got this message:
Plugin 'SMS' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml
with Cordova 5.1.1.
On Android, it works perfect.

Am I missing something?

**Comment by chrisbenseler** [comment]
Oh, I guess this is only intended to work for Android?

**Comment by floatinghotpot** [comment]
Yes, only android is implemented
