### ISSUE TITLE
Not working on phonegap developer app

### ISSUE THREAD

**Issue by Saurabh995** [floatinghotpot/cordova-plugin-sms#21]
None of the functionalities is working on phonegap developer app(Android) . Is purchasing the license is required for testing and development?

**Comment by KaptainKrayola** [comment]
I had this same problem with another plugin and it's because the phonegap developer app doesn't support 3rd party plugins unless they are pure javascript.

**Comment by floatinghotpot** [comment]
When use 3rd party plugin in PhoneGap build service, please make sure following line is written in your config.xml:
```xml
<gap:plugin name="cordova-plugin-sms" source="npm" />
```
