### ISSUE TITLE
List all sms

### ISSUE THREAD

**Issue by siddmegadeth** [floatinghotpot/cordova-plugin-sms#27]
currently only 10 sms are disaplyed. how to list all sms.
what is the use of filter and there are no docs.
if u could have added a donate button people would have supported u but u seems too greedy.
how could 1 pay 30$ when i canot confirm the whole plugins with params etc.

**Comment by floatinghotpot** [comment]
It's a deal to pay for my time and support, not a donation. 

$30 is very cheap, as time is valuable. If you cannot afford it, please don't say other people is greedy. As you are the first one to say that.

It's a deal, no discount. :-)

**Comment by onglipo** [comment]
Where do I buy?

**Comment by randomprimate** [comment]
@floatinghotpot got a license and added it as the emailed example but still hitting a limit. Any thoughts?

**Comment by floatinghotpot** [comment]
Please see the example code here:
https://github.com/floatinghotpot/cordova-plugin-sms/tree/master/docs#listsms

```javascript
maxCount : 10, // count of SMS to return each time, default 10
```

If you want more as max limit, just pass it.

**Comment by randomprimate** [comment]
@onglipo here's the link where I bought it https://github.com/floatinghotpot/cordova-plugin-sms#credits

**Comment by randomprimate** [comment]
@floatinghotpot awesome, thanks for quick reply. I'd consider this issue closed btw.
