### ISSUE TITLE
Intercept not working

### ISSUE THREAD

**Issue by prantikv** [floatinghotpot/cordova-plugin-sms#29]
I am using this plugin and loving it. Thanks and keep up the good work.

Everything else works fine except that found that when i use intercept the sms still goes through to the default sms app.

I am using cordova 5.0.0 and have checked for android 4.4.2 and 5.0

I am using the following code for intercept 

```
     interceptTrue(){
         if(SMS) SMS.enableIntercept(true, function(success){
              console.log("interceptTrue  "+ success);
              }, function(error){
             console.log("interceptTrue "+error);
           });
      }
```

I am not getting any errors and when the success callback returns "OK".

Notice that i am using the first parameter as Boolean true, From what i could tell that is the correct way but do let me know otherwise.

-Thanks

**Comment by floatinghotpot** [comment]
As to intercept, it depends on the Android OS version. It’s quite okay on version before Android 4.4+. 

But after v4.4, as Google add very strict security control after v4.4, and only the system default SMS app can intercept SMS. If your app is not the default SMS app, you can still get & read SMS, but cannot intercept (remove SMS before other app get it) any more.
