### ISSUE TITLE
Android M wont ask for sms permissions

### ISSUE THREAD

**Issue by bitgandtter** [floatinghotpot/cordova-plugin-sms#30]
I have an app that listen to incoming sms to detect confirmation code for registration action and on android M it does not request the permissions to the user so it does not detect the incoming sms.

Previously versions 4 >= 5 <= works just fine.

UPDATE:

if y try to send an SMS i get this error

uid 10147 does not have android.permission.SEND_SMS.

How can we force android to request SMS rights

**Comment by Dineshrajaa** [comment]
+1

**Comment by Alexintosh** [comment]
Any idea on this?

**Comment by iOlivier** [comment]
+1

**Comment by Alexintosh** [comment]
+101

**Comment by thisisirfan** [comment]
> I have an app that listen to incoming sms to detect confirmation code for registration action and on android M it does not request the permissions to the user so it does not detect the incoming sms.
> 
> Previously versions 4 >= 5 <= works just fine.
> 
> UPDATE:
> 
> if y try to send an SMS i get this error
> 
> uid 10147 does not have android.permission.SEND_SMS.
> 
> How can we force android to request SMS rights

Did you find any solution?

**Comment by thisisirfan** [comment]
this might help: [https://stackoverflow.com/a/32636039/4754175](url)
