### ISSUE TITLE
Error in Success callbackId: SMS225915513 : ReferenceError: update is not defined

### ISSUE THREAD

**Issue by muhsin-k** [floatinghotpot/cordova-plugin-sms#37]
When i give 

```
 if (window.cordova) {
     if (SMS) SMS.startWatch(function() {
         update('watching', 'watching started');
     }, function() {
         updateStatus('failed to start watching');
     });
 }

```

I am getting an error like this ,
**SMS225915513 : ReferenceError: update is not defined**

**Comment by gion** [comment]
If you're just copy-pasting from the examples provided in the [docs](https://github.com/floatinghotpot/cordova-plugin-sms/tree/master/docs#startwatch), you should probably implement the `update` and `updateStatus` functions. They aren't implemented... they are just there to help you make a better picture of how to use the plugin.
