### ISSUE TITLE
Plugin support ?

### ISSUE THREAD

**Issue by gonadn** [floatinghotpot/cordova-plugin-sms#59]
Does this plugin support Android and iOS?

**Comment by floatinghotpot** [comment]
No, this plugin only support Android platform. As iOS is more strict and does not allow access your SMS database.

**Comment by pedrotcm** [comment]
And Windows phone, is also not allowed?

**Comment by brody2consult** [comment]
https://github.com/cordova-sms/cordova-sms-plugin supports Android, iOS, Windows

**Comment by pedrotcm** [comment]
Yes @brodybits. I meant about reading the sms.
