### ISSUE TITLE
Getting top 10 messages only

### ISSUE THREAD

**Issue by anup5708** [floatinghotpot/cordova-plugin-sms#60]
Hi,

I follow the below code.

```
 if(window.SMS) window.SMS.listSMS({},data=>{
            console.log(data);
            this.smses=data;
    },error=>{
      console.log(error);
    });
```
In my Inbox I have almost more than 10 messages, and it showing me top 10 messages only.
.
Please help if I am doing anything wrong.

**Comment by shineirvin** [comment]
Help, i cant even run the demo.
when i try to alert(SMS) ( no response at all )
when i try to alert(window.SMS)  ( undefined ) 
what did i do wrong here ? 
Please help.

**Comment by anup5708** [comment]
HI @shineirvin 

Just declare below line above your class

**declare var window: any;**
