### ISSUE TITLE
listSMS problem

### ISSUE THREAD

**Issue by ostdt** [floatinghotpot/cordova-plugin-sms#8]
I have tried to use the listSMS method and it seems to work ok. But I have problems with interpreting two fields in the JSON file that it returns. The two fields are date_sent and date. They contain just numbers, so I guess they are supposed to be UNIX style dates (i.e. milliseconds from the epoch). Is that a correct assumption? When accessed from javascript though, they are sometimes negative and they appear to be to small. Is there a conversion problem between Java and Javascript?

**Comment by LeandroBarone** [comment]
Same problem here. I'm getting date_sent and date, but I don't know what to do with them. They are not UNIX timestamps (seconds nor milliseconds). And sometimes they are 0. Some examples from a single listSMS request:

932963759
358472368
280196220
0

Thanks in advance for your help.

**Comment by simokhalil** [comment]
Got the exactly same problem, with dates like -743145598.
All date and date_sent are negavtive values for me.
Has anyone managed to interpret these fields ?

**Comment by Aadi21** [comment]
I decompiled cordova-sms.jar, and the code to get SMS from android.database.Cursor uses getInt() instead of getLong() in method getJsonFromCursor(). This may be the reason for incorrect date values.
I am not able to recompile the updated code into jar file. Any help?

**Comment by simokhalil** [comment]
@Aadi21 Would you please provide me your modified java file please, so I can include it and make a fork.

**Comment by Aadi21** [comment]
@simokhalil  Could you please share your email address, and I will send the modified file to you. Or let me know how can I share the same.

**Comment by simokhalil** [comment]
Could you upload it into DevHost (http://d-h.st/) and share the link to it please

**Comment by Aadi21** [comment]
@simokhalil there you go: http://d-h.st/wUt1   Hope it helps.

**Comment by floatinghotpot** [comment]
Update: Now the java code is open sourced, welcome to fork and improve it.

**Comment by shineirvin** [comment]
Can you show me the javascript code ?
I cant even run the test code.
alert(window.SMS) no response
alert(SMS) undefined.
Please help me.
